spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:./h2/data
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    data: classpath:h2/init.sql
    schema: classpath:h2/schema.sql
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    database: H2
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: none
        show_sql: true
    show-sql: true
