spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:./h2/data
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    data: classpath:h2/init.sql
    schema: classpath:h2/schema.sql
